# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ijudaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ijudaApp

    pod 'Alamofire', '~> 5.0.0-rc.2'


  target 'ijudaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ijudaAppUITests' do
    # Pods for testing
  end

end
